/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package coursera_algorithms.week_1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        HelloWorld classUnderTest = new HelloWorld();
        assertNotNull(classUnderTest);
    }
}
